# Generated by Django 4.1.5 on 2023-04-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
